version: '3'
services: 
    postgres:
        image: postgres:13
        container_name: postgres
        restart: 'always'
        environment: 
              POSTGRES_PASSWORD: godemo
        volumes: 
            - "/home/$USER/postgres_go:/var/lib/postgresql/data"
        ports: 
            - 5432:5432